kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-from-observability-ns
  namespace: mistral-serve
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: observability
  policyTypes:
    - Ingress

