---
receivers:
  prometheus:
    config:
      scrape_configs:
      #- job_name: 'pmproxy-rhel-ai'
      #  scrape_interval: 5s
      #  static_configs:
      #    - targets: ['0.0.0.0:44322']
      - job_name: 'vllm'
        scrape_interval: 5s
        static_configs:
          - targets: ['0.0.0.0:8000']

  otlp:
    protocols:
      http:
      grpc:

  journald:
    units:
    #    - kepler
    #    - opentelemetry-collector
    priority: info

processors:
  #filter:
  #  error_mode: ignore
  #  metrics:
  #    datapoint:
  #      # these pcp metrics were causing errors so removed them
  #      - metric.name == "rhelai_mem_vmstat_pgscan_kswapd_total"
  #      - metric.name == "rhelai_mem_vmstat_pgscan_direct_total"

  cumulativetodelta:
  batch:
    send_batch_size: 100
    timeout: 1s
  resourcedetection/system:
    detectors: ["system"]

  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25

extensions:
  file_storage:
    directory: /otc
    timeout: 10s
    compaction:
      on_start: true 
      directory: /tmp/
      max_transaction_size: 65536
    fsync: false 

exporters:
  otlp:
    endpoint: "localhost:4317"
    sending_queue:
      enabled: true
      storage: file_storage
  #otlphttp/dynatrace:
  #  endpoint: "https://ENVIRONMENT.live.dynatrace.com/api/v2/otlp"
  #  headers:
  #    Authorization: "Api-Token xxxx.XXXX.XXXXXX"
  #otlphttp/ocp:
  #  endpoint: https://otlp-http-otlp-receiver-route-observability.apps.ocp-beta-test.nerc.mghpcc.org
  #  tls:
  #    insecure: false
  #    cert_file: /certs/server.crt
  #    key_file: /certs/server.key
  #    ca_file: /certs/ca.crt

  prometheus:
    endpoint: 0.0.0.0:8888

  debug:
    verbosity: basic

service:
  extensions: [file_storage]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, cumulativetodelta, memory_limiter]
      exporters: [prometheus, debug]
